# if the environment does not specify build type, set to Debug
IF (NOT CMAKE_BUILD_TYPE)
    set(CMAKE_BUILD_TYPE "Debug"
            CACHE STRING "Choose the type of build, options are: Debug Release RelWithDebInfo MinSizeRel."
            FORCE)
ENDIF ()

SET(LD_SYS_LIBS "-Wl,--start-group -lstdc++ -lsupc++ -lm -lc -lgcc -lnosys  -Wl,--end-group")


if (${BOARD_SELECT} STREQUAL "767")
    SET(CMAKE_C_FLAGS "-std=gnu11 -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fmessage-length=0 -fno-exceptions -ffunction-sections -fdata-sections -funsigned-char -MMD -fno-delete-null-pointer-checks -fomit-frame-pointer -Os -g -DMBED_TRAP_ERRORS_ENABLED=1 -mcpu=cortex-m7 -mthumb -mfpu=fpv5-d16 -mfloat-abi=softfp -include ../mbed_config.h")
    SET(CMAKE_CXX_FLAGS "-std=gnu++14 -fno-rtti -Wvla -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fmessage-length=0 -fno-exceptions -ffunction-sections -fdata-sections -funsigned-char -MMD -fno-delete-null-pointer-checks -fomit-frame-pointer -Os -g -DMBED_TRAP_ERRORS_ENABLED=1 -mcpu=cortex-m7 -mthumb -mfpu=fpv5-d16 -mfloat-abi=softfp  -include ../mbed_config.h")
    SET(CMAKE_ASM_FLAGS "-x assembler-with-cpp -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fmessage-length=0 -fno-exceptions -ffunction-sections -fdata-sections -funsigned-char -MMD -fno-delete-null-pointer-checks -fomit-frame-pointer -Os -g -DMBED_TRAP_ERRORS_ENABLED=1 -mcpu=cortex-m7 -mthumb -mfpu=fpv5-d16 -mfloat-abi=softfp  -include ../mbed_config.h")
    SET(CMAKE_CXX_LINK_FLAGS "-Wl,--gc-sections -Wl,--wrap,main -Wl,--wrap,__malloc_r -Wl,--wrap,__free_r -Wl,--wrap,__realloc_r -Wl,--wrap,__memalign_r -Wl,--wrap,__calloc_r -Wl,--wrap,exit -Wl,--wrap,atexit -Wl,-n -mcpu=cortex-m7 -mthumb -mfpu=fpv5-d16 -mfloat-abi=softfp ")
    SET(CMAKE_CXX_LINK_FLAGS "${CMAKE_CXX_LINK_FLAGS} ${LD_SYS_LIBS} -T ${CMAKE_BINARY_DIR}/${PROJECT_NAME}_pp.link_script.ld")
elseif(${BOARD_SELECT} STREQUAL "746")
    SET(CMAKE_C_FLAGS "-std=gnu11 -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fmessage-length=0 -fno-exceptions -ffunction-sections -fdata-sections -funsigned-char -MMD -fomit-frame-pointer -Os -g -DMBED_TRAP_ERRORS_ENABLED=1 -DMBED_MINIMAL_PRINTF -mcpu=cortex-m7 -mthumb -mfpu=fpv5-sp-d16 -mfloat-abi=softfp -DMBED_ROM_START=0x8000000 -DMBED_ROM_SIZE=0x100000 -DMBED_ROM1_START=0x200000 -DMBED_ROM1_SIZE=0x100000 -DMBED_RAM1_START=0x20000000 -DMBED_RAM1_SIZE=0x10000 -DMBED_RAM_START=0x20010000 -DMBED_RAM_SIZE=0x40000 -include ../mbed_config.h")
    SET(CMAKE_CXX_FLAGS "-std=gnu++14 -fno-rtti -Wvla -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fmessage-length=0 -fno-exceptions -ffunction-sections -fdata-sections -funsigned-char -MMD -fomit-frame-pointer -Os -g -DMBED_TRAP_ERRORS_ENABLED=1 -DMBED_MINIMAL_PRINTF -mcpu=cortex-m7 -mthumb -mfpu=fpv5-sp-d16 -mfloat-abi=softfp -DMBED_ROM_START=0x8000000 -DMBED_ROM_SIZE=0x100000 -DMBED_ROM1_START=0x200000 -DMBED_ROM1_SIZE=0x100000 -DMBED_RAM1_START=0x20000000 -DMBED_RAM1_SIZE=0x10000 -DMBED_RAM_START=0x20010000 -DMBED_RAM_SIZE=0x40000  -include ../mbed_config.h")
    SET(CMAKE_ASM_FLAGS "-x assembler-with-cpp -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fmessage-length=0 -fno-exceptions -ffunction-sections -fdata-sections -funsigned-char -MMD -fomit-frame-pointer -Os -g -DMBED_TRAP_ERRORS_ENABLED=1 -DMBED_MINIMAL_PRINTF -mcpu=cortex-m7 -mthumb -mfpu=fpv5-sp-d16 -mfloat-abi=softfp  -include ../mbed_config.h")
    SET(CMAKE_CXX_LINK_FLAGS "-Wl,--gc-sections -Wl,--wrap,main -Wl,--wrap,__malloc_r -Wl,--wrap,__free_r -Wl,--wrap,__realloc_r -Wl,--wrap,__memalign_r -Wl,--wrap,__calloc_r -Wl,--wrap,exit -Wl,--wrap,atexit -Wl,-n -mcpu=cortex-m7 -mthumb -mfpu=fpv5-sp-d16 -mfloat-abi=softfp -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fmessage-length=0 -fno-exceptions -ffunction-sections -fdata-sections -funsigned-char -MMD -fomit-frame-pointer -Os -g -DMBED_TRAP_ERRORS_ENABLED=1 -DMBED_MINIMAL_PRINTF -mcpu=cortex-m7 -mthumb -mfpu=fpv5-sp-d16 -mfloat-abi=softfp -DMBED_ROM_START=0x8000000 -DMBED_ROM_SIZE=0x100000 -DMBED_ROM1_START=0x200000 -DMBED_ROM1_SIZE=0x100000 -DMBED_RAM1_START=0x20000000 -DMBED_RAM1_SIZE=0x10000 -DMBED_RAM_START=0x20010000 -DMBED_RAM_SIZE=0x40000 -DMBED_BOOT_STACK_SIZE=4096 -DXIP_ENABLE=0  -L${CMAKE_CURRENT_SOURCE_DIR}/mbed/TARGET_NUCLEO_F746ZG/TOOLCHAIN_GCC_ARM ")
    SET(CMAKE_CXX_LINK_FLAGS "${CMAKE_CXX_LINK_FLAGS} ${LD_SYS_LIBS} -T ${CMAKE_BINARY_DIR}/${PROJECT_NAME}_pp.link_script.ld")
elseif(${BOARD_SELECT} STREQUAL "446")
    SET(CMAKE_C_FLAGS "-std=gnu11 -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fmessage-length=0 -fno-exceptions -ffunction-sections -fdata-sections -funsigned-char -MMD -fomit-frame-pointer -Os -g -DMBED_TRAP_ERRORS_ENABLED=1 -DMBED_MINIMAL_PRINTF -mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -DMBED_ROM_START=0x8000000 -DMBED_ROM_SIZE=0x80000 -DMBED_RAM_START=0x20000000 -DMBED_RAM_SIZE=0x20000 -include ../mbed_config.h")
    SET(CMAKE_CXX_FLAGS "-std=gnu++14 -fno-rtti -Wvla -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fmessage-length=0 -fno-exceptions -ffunction-sections -fdata-sections -funsigned-char -MMD -fomit-frame-pointer -Os -g -DMBED_TRAP_ERRORS_ENABLED=1 -DMBED_MINIMAL_PRINTF -mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -DMBED_ROM_START=0x8000000 -DMBED_ROM_SIZE=0x80000 -DMBED_RAM_START=0x20000000 -DMBED_RAM_SIZE=0x20000  -include ../mbed_config.h")
    SET(CMAKE_ASM_FLAGS "-x assembler-with-cpp -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fmessage-length=0 -fno-exceptions -ffunction-sections -fdata-sections -funsigned-char -MMD -fomit-frame-pointer -Os -g -DMBED_TRAP_ERRORS_ENABLED=1 -DMBED_MINIMAL_PRINTF -mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=softfp  -include ../mbed_config.h")
    SET(CMAKE_CXX_LINK_FLAGS "-Wl,--gc-sections -Wl,--wrap,main -Wl,--wrap,__malloc_r -Wl,--wrap,__free_r -Wl,--wrap,__realloc_r -Wl,--wrap,__memalign_r -Wl,--wrap,__calloc_r -Wl,--wrap,exit -Wl,--wrap,atexit -Wl,-n -mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fmessage-length=0 -fno-exceptions -ffunction-sections -fdata-sections -funsigned-char -MMD -fomit-frame-pointer -Os -g -DMBED_TRAP_ERRORS_ENABLED=1 -DMBED_MINIMAL_PRINTF -mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -DMBED_ROM_START=0x8000000 -DMBED_ROM_SIZE=0x80000 -DMBED_RAM_START=0x20000000 -DMBED_RAM_SIZE=0x20000 -DMBED_BOOT_STACK_SIZE=4096 -DXIP_ENABLE=0  -L${CMAKE_CURRENT_SOURCE_DIR}/mbed/TARGET_NUCLEO_F446RE/TOOLCHAIN_GCC_ARM ")
    SET(CMAKE_CXX_LINK_FLAGS "${CMAKE_CXX_LINK_FLAGS} ${LD_SYS_LIBS} -T ${CMAKE_BINARY_DIR}/${PROJECT_NAME}_pp.link_script.ld")
endif()

if (${SERIES_SELECT} STREQUAL "F7")
    ADD_DEFINITIONS(
            -DARM_MATH_CM7
            -DDEVICE_ANALOGIN=1
            -DDEVICE_ANALOGOUT=1
            -DDEVICE_CAN=1
            -DDEVICE_CRC=1
            -DDEVICE_EMAC=1
            -DDEVICE_FLASH=1
            -DDEVICE_I2C=1
            -DDEVICE_I2CSLAVE=1
            -DDEVICE_I2C_ASYNCH=1
            -DDEVICE_INTERRUPTIN=1
            -DDEVICE_LPTICKER=1
            -DDEVICE_PORTIN=1
            -DDEVICE_PORTINOUT=1
            -DDEVICE_PORTOUT=1
            -DDEVICE_PWMOUT=1
            -DDEVICE_RTC=1
            -DDEVICE_SERIAL=1
            -DDEVICE_SERIAL_ASYNCH=1
            -DDEVICE_SLEEP=1
            -DDEVICE_SPI=1
            -DDEVICE_SPISLAVE=1
            -DDEVICE_SPI_ASYNCH=1
            -DDEVICE_STDIO_MESSAGES=1
            -DDEVICE_TRNG=1
            -DDEVICE_USTICKER=1
            -DFEATURE_LWIP=1
            -DMBED_BUILD_TIMESTAMP=1580738482.6158805
            -DTARGET_CORTEX
            -DTARGET_CORTEX_M
            -DTARGET_FAMILY_STM32
            -DTARGET_FF_ARDUINO
            -DTARGET_LIKE_CORTEX_M7
            -DTARGET_LIKE_MBED
            -DTARGET_M7
            -DTARGET_RELEASE
            -DTARGET_RTOS_M4_M7
            -DTARGET_STM
            -DTARGET_STM32F7
            -DTARGET_STM_EMAC
            -DTOOLCHAIN_GCC
            -DTOOLCHAIN_GCC_ARM
            -DTRANSACTION_QUEUE_SIZE_SPI=2
            -DUSBHOST_OTHER
            -D__CMSIS_RTOS
            -D__CORTEX_M7
            -D__FPU_PRESENT=1
            -D__MBED_CMSIS_RTOS_CM
            -D__MBED__=1
    )
elseif (${SERIES_SELECT} STREQUAL "F4")
    ADD_DEFINITIONS(
            -DARM_MATH_CM4
            -DDEVICE_ANALOGIN=1
            -DDEVICE_ANALOGOUT=1
            -DDEVICE_CAN=1
            -DDEVICE_FLASH=1
            -DDEVICE_I2C=1
            -DDEVICE_I2CSLAVE=1
            -DDEVICE_I2C_ASYNCH=1
            -DDEVICE_INTERRUPTIN=1
            -DDEVICE_LPTICKER=1
            -DDEVICE_MPU=1
            -DDEVICE_PORTIN=1
            -DDEVICE_PORTINOUT=1
            -DDEVICE_PORTOUT=1
            -DDEVICE_PWMOUT=1
            -DDEVICE_RESET_REASON=1
            -DDEVICE_RTC=1
            -DDEVICE_SERIAL=1
            -DDEVICE_SERIAL_ASYNCH=1
            -DDEVICE_SERIAL_FC=1
            -DDEVICE_SLEEP=1
            -DDEVICE_SPI=1
            -DDEVICE_SPISLAVE=1
            -DDEVICE_SPI_ASYNCH=1
            -DDEVICE_STDIO_MESSAGES=1
            -DDEVICE_USTICKER=1
            -DDEVICE_WATCHDOG=1
            -DMBED_BUILD_TIMESTAMP=1623917202.9403827
            -DSTM32F446xx
            -DTARGET_CORTEX
            -DTARGET_CORTEX_M
            -DTARGET_FF_ARDUINO
            -DTARGET_FF_MORPHO
            -DTARGET_LIKE_CORTEX_M4
            -DTARGET_LIKE_MBED
            -DTARGET_M4
            -DTARGET_MCU_STM32
            -DTARGET_NAME=NUCLEO_F446RE
            -DTARGET_NUCLEO_F446RE
            -DTARGET_RELEASE
            -DTARGET_RTOS_M4_M7
            -DTARGET_STM
            -DTARGET_STM32F4
            -DTARGET_STM32F446xE
            -DTOOLCHAIN_GCC
            -DTOOLCHAIN_GCC_ARM
            -DTRANSACTION_QUEUE_SIZE_SPI=2
            -DUSE_FULL_LL_DRIVER
            -DUSE_HAL_DRIVER
            -D__CMSIS_RTOS
            -D__CORTEX_M4
            -D__FPU_PRESENT=1
            -D__MBED_CMSIS_RTOS_CM
            -D__MBED__=1
    )
endif()

if (${BOARD_SELECT} STREQUAL "767")
    ADD_DEFINITIONS(
            -DCOMPONENT_FLASHIAP=1
            -DSTM32F767xx
            -DTARGET_NAME=NUCLEO_F767ZI
            -DTARGET_NUCLEO_F767ZI
            -DTARGET_STM32F767ZI
            -DTARGET_STM32F767xI
            -DTARGET_STM32F767
    )
    INCLUDE_DIRECTORIES(
            mbed/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/device
            mbed/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/TARGET_NUCLEO_F767ZI
            mbed/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI
            mbed/targets/TARGET_STM/TARGET_STM32F7/device
            mbed/targets/TARGET_STM/TARGET_STM32F7
    )
elseif(${BOARD_SELECT} STREQUAL "746")
    ADD_DEFINITIONS(
            -DSTM32F746xx
            -DTARGET_NAME=NUCLEO_F746ZG
            -DTARGET_NUCLEO_F746ZG
            -DTARGET_STM32F746ZG
            -DTARGET_STM32F746xG
    )
    INCLUDE_DIRECTORIES(
            mbed/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/device
            mbed/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/TARGET_NUCLEO_F746ZG
            mbed/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG
            mbed/targets/TARGET_STM/TARGET_STM32F7/device
            mbed/targets/TARGET_STM/TARGET_STM32F7
    )
elseif(${BOARD_SELECT} STREQUAL "446")
    INCLUDE_DIRECTORIES(
            mbed/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F446xE/TARGET_NUCLEO_F446RE
            mbed/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F446xE/device
            mbed/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F446xE
            mbed/targets/TARGET_STM/TARGET_STM32F4/device
            mbed/targets/TARGET_STM/TARGET_STM32F4
    )
endif()
INCLUDE_DIRECTORIES(
        mbed/targets/TARGET_STM
        mbed/platform
        mbed/hal/storage_abstraction
        mbed/hal
        mbed/drivers
        mbed/cmsis/TARGET_CORTEX_M
        mbed/cmsis
        mbed
        ./
)

if (${BOARD_SELECT} STREQUAL "767")
    set(board_specific_files
            mbed/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/TARGET_NUCLEO_F767ZI/PeripheralNames.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/TARGET_NUCLEO_F767ZI/PeripheralPins.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/TARGET_NUCLEO_F767ZI/PinNames.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/TARGET_NUCLEO_F767ZI/system_clock.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/device/TOOLCHAIN_GCC_ARM/startup_stm32f767xx.S
            mbed/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/device/cmsis.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/device/cmsis_nvic.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/device/flash_data.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/device/stm32f767xx.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/device/stm32f7xx.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/device/system_stm32f7xx.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/device/us_ticker_data.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/objects.h
            )
elseif(${BOARD_SELECT} STREQUAL "746")
    set(board_specific_files
            mbed/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/TARGET_NUCLEO_F746ZG/PeripheralNames.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/TARGET_NUCLEO_F746ZG/PeripheralPins.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/TARGET_NUCLEO_F746ZG/PinNames.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/TARGET_NUCLEO_F746ZG/system_clock.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/device/TOOLCHAIN_GCC_ARM/startup_stm32f746xx.S
            mbed/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/device/cmsis.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/device/cmsis_nvic.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/device/flash_data.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/device/stm32f7xx.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/device/stm32f746xx.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/device/system_stm32f7xx.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/device/us_ticker_data.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/objects.h
    )
elseif(${BOARD_SELECT} STREQUAL "446")
    set(board_specific_files
            mbed/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F446xE/TARGET_NUCLEO_F446RE/PeripheralNames.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F446xE/TARGET_NUCLEO_F446RE/PeripheralPins.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F446xE/TARGET_NUCLEO_F446RE/PinNames.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F446xE/TARGET_NUCLEO_F446RE/system_clock.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F446xE/device/TOOLCHAIN_GCC_ARM/startup_stm32f446xx.S
            mbed/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F446xE/device/cmsis.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F446xE/device/cmsis_nvic.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F446xE/device/flash_data.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F446xE/device/stm32f4xx.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F446xE/device/stm32f446xx.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F446xE/device/system_stm32f4xx.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F446xE/device/us_ticker_data.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F446xE/objects.h
            )
endif ()

if (${SERIES_SELECT} STREQUAL "F7")
    set(series_specific_files
            mbed/targets/TARGET_STM/lp_ticker.c

            mbed/targets/TARGET_STM/TARGET_STM32F7/analogin_device.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/analogout_device.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/can_device.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/common_objects.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32_hal_legacy.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_adc.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_adc.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_adc_ex.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_adc_ex.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_can.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_can.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_can_legacy.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_can_legacy.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_cec.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_cec.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_conf.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_cortex.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_cortex.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_crc.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_crc.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_crc_ex.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_crc_ex.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_cryp.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_cryp.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_cryp_ex.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_cryp_ex.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_dac.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_dac.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_dac_ex.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_dac_ex.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_dcmi.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_dcmi.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_dcmi_ex.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_dcmi_ex.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_def.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_dfsdm.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_dfsdm.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_dma.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_dma.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_dma2d.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_dma2d.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_dma_ex.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_dma_ex.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_dsi.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_dsi.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_eth.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_eth.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_flash.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_flash.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_flash_ex.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_flash_ex.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_gpio.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_gpio.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_gpio_ex.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_hash.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_hash.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_hash_ex.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_hash_ex.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_hcd.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_hcd.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_i2c.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_i2c.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_i2c_ex.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_i2c_ex.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_i2s.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_i2s.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_irda.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_irda.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_irda_ex.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_iwdg.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_iwdg.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_jpeg.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_jpeg.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_lptim.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_lptim.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_ltdc.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_ltdc.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_ltdc_ex.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_ltdc_ex.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_mdios.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_mdios.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_mmc.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_mmc.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_nand.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_nand.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_nor.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_nor.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_pcd.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_pcd.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_pcd_ex.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_pcd_ex.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_pwr.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_pwr.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_pwr_ex.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_pwr_ex.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_qspi.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_qspi.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_rcc.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_rcc.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_rcc_ex.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_rcc_ex.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_rng.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_rng.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_rtc.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_rtc.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_rtc_ex.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_rtc_ex.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_sai.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_sai.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_sai_ex.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_sai_ex.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_sd.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_sd.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_sdram.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_sdram.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_smartcard.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_smartcard.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_smartcard_ex.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_smartcard_ex.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_smbus.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_smbus.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_spdifrx.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_spdifrx.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_spi.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_spi.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_spi_ex.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_spi_ex.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_sram.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_sram.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_tim.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_tim.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_tim_ex.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_tim_ex.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_uart.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_uart.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_uart_ex.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_usart.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_usart.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_usart_ex.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_wwdg.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_wwdg.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_adc.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_adc.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_bus.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_cortex.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_crc.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_crc.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_dac.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_dac.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_dma.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_dma.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_dma2d.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_dma2d.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_exti.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_exti.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_fmc.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_fmc.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_gpio.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_gpio.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_i2c.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_i2c.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_iwdg.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_lptim.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_lptim.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_pwr.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_pwr.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_rcc.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_rcc.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_rng.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_rng.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_rtc.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_rtc.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_sdmmc.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_sdmmc.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_spi.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_spi.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_system.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_tim.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_tim.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_usart.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_usart.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_usb.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_usb.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_utils.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_utils.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_wwdg.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/device/system_stm32f7xx.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/flash_api.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/gpio_irq_device.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/gpio_irq_device.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/i2c_device.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/pin_device.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/pwmout_device.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/pwmout_device.h
            mbed/targets/TARGET_STM/TARGET_STM32F7/serial_device.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/spi_api.c
            mbed/targets/TARGET_STM/TARGET_STM32F7/spi_device.h
            )
elseif (${SERIES_SELECT} STREQUAL "F4")
    set(series_specific_files
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32_hal_legacy.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_adc.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_adc.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_adc_ex.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_adc_ex.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_can.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_can.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_can_legacy.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_can_legacy.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_cec.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_cec.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_conf.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_cortex.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_cortex.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_crc.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_crc.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_cryp.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_cryp.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_cryp_ex.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_cryp_ex.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dac.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dac.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dac_ex.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dac_ex.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dcmi.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dcmi.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dcmi_ex.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dcmi_ex.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_def.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dfsdm.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dfsdm.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dma.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dma.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dma2d.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dma2d.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dma_ex.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dma_ex.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dsi.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dsi.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_eth.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_eth.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_flash.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_flash.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_flash_ex.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_flash_ex.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_flash_ramfunc.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_flash_ramfunc.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_fmpi2c.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_fmpi2c.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_fmpi2c_ex.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_fmpi2c_ex.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_gpio.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_gpio.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_gpio_ex.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_hash.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_hash.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_hash_ex.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_hash_ex.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_hcd.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_hcd.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_i2c.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_i2c.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_i2c_ex.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_i2c_ex.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_i2s.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_i2s.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_i2s_ex.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_i2s_ex.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_irda.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_irda.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_iwdg.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_iwdg.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_lptim.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_lptim.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_ltdc.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_ltdc.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_ltdc_ex.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_ltdc_ex.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_mmc.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_mmc.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_nand.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_nand.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_nor.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_nor.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_pccard.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_pccard.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_pcd.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_pcd.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_pcd_ex.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_pcd_ex.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_pwr.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_pwr.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_pwr_ex.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_pwr_ex.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_qspi.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_qspi.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_rcc.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_rcc.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_rcc_ex.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_rcc_ex.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_rng.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_rng.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_rtc.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_rtc.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_rtc_ex.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_rtc_ex.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_sai.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_sai.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_sai_ex.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_sai_ex.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_sd.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_sd.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_sdram.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_sdram.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_smartcard.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_smartcard.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_spdifrx.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_spdifrx.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_spi.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_spi.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_sram.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_sram.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_tim.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_tim.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_tim_ex.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_tim_ex.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_uart.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_uart.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_usart.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_usart.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_wwdg.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_wwdg.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_adc.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_adc.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_bus.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_cortex.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_crc.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_crc.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_dac.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_dac.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_dma.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_dma.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_dma2d.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_dma2d.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_exti.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_exti.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_fmc.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_fmc.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_fsmc.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_fsmc.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_gpio.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_gpio.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_i2c.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_i2c.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_iwdg.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_lptim.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_lptim.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_pwr.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_pwr.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_rcc.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_rcc.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_rng.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_rng.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_rtc.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_rtc.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_sdmmc.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_sdmmc.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_spi.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_spi.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_system.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_tim.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_tim.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_usart.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_usart.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_usb.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_usb.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_utils.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_utils.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_wwdg.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device/system_stm32f4xx.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/analogin_device.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/analogout_device.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/can_device.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/common_objects.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/device.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/flash_api.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/gpio_irq_device.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/gpio_irq_device.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/i2c_device.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/pin_device.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/pwmout_device.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/pwmout_device.h
            mbed/targets/TARGET_STM/TARGET_STM32F4/serial_device.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/spi_api.c
            mbed/targets/TARGET_STM/TARGET_STM32F4/spi_device.h
            )
endif()

set(libmbed_files
        mbed/cmsis/RTE_Components.h
        mbed/cmsis/TARGET_CORTEX_M/arm_math.h
        mbed/cmsis/TARGET_CORTEX_M/cmsis_armcc.h
        mbed/cmsis/TARGET_CORTEX_M/cmsis_armclang.h
        mbed/cmsis/TARGET_CORTEX_M/cmsis_compiler.h
        mbed/cmsis/TARGET_CORTEX_M/cmsis_gcc.h
        mbed/cmsis/TARGET_CORTEX_M/cmsis_iccarm.h
        mbed/cmsis/TARGET_CORTEX_M/cmsis_version.h
        mbed/cmsis/TARGET_CORTEX_M/core_armv8mbl.h
        mbed/cmsis/TARGET_CORTEX_M/core_armv8mml.h
        mbed/cmsis/TARGET_CORTEX_M/core_cm0.h
        mbed/cmsis/TARGET_CORTEX_M/core_cm0plus.h
        mbed/cmsis/TARGET_CORTEX_M/core_cm23.h
        mbed/cmsis/TARGET_CORTEX_M/core_cm3.h
        mbed/cmsis/TARGET_CORTEX_M/core_cm33.h
        mbed/cmsis/TARGET_CORTEX_M/core_cm4.h
        mbed/cmsis/TARGET_CORTEX_M/core_cm7.h
        mbed/cmsis/TARGET_CORTEX_M/core_cmSecureAccess.h
        mbed/cmsis/TARGET_CORTEX_M/core_sc000.h
        mbed/cmsis/TARGET_CORTEX_M/core_sc300.h
        mbed/cmsis/TARGET_CORTEX_M/mbed_tz_context.c
        mbed/cmsis/TARGET_CORTEX_M/mpu_armv7.h
        mbed/cmsis/TARGET_CORTEX_M/mpu_armv8.h
        mbed/cmsis/TARGET_CORTEX_M/tz_context.h
        mbed/cmsis/mbed_cmsis_conf.h
        mbed/drivers/AnalogIn.cpp
        mbed/drivers/AnalogIn.h
        mbed/drivers/AnalogOut.h
        mbed/drivers/BusIn.cpp
        mbed/drivers/BusIn.h
        mbed/drivers/BusInOut.cpp
        mbed/drivers/BusInOut.h
        mbed/drivers/BusOut.cpp
        mbed/drivers/BusOut.h
        mbed/drivers/CAN.cpp
        mbed/drivers/CAN.h
        mbed/drivers/DigitalIn.h
        mbed/drivers/DigitalInOut.h
        mbed/drivers/DigitalOut.h
        mbed/drivers/Ethernet.cpp
        mbed/drivers/Ethernet.h
        mbed/drivers/FlashIAP.cpp
        mbed/drivers/FlashIAP.h
        mbed/drivers/I2C.cpp
        mbed/drivers/I2C.h
        mbed/drivers/I2CSlave.cpp
        mbed/drivers/I2CSlave.h
        mbed/drivers/InterruptIn.cpp
        mbed/drivers/InterruptIn.h
        mbed/drivers/InterruptManager.cpp
        mbed/drivers/InterruptManager.h
        mbed/drivers/LowPowerTicker.h
        mbed/drivers/LowPowerTimeout.h
        mbed/drivers/LowPowerTimer.h
        mbed/drivers/MbedCRC.cpp
        mbed/drivers/MbedCRC.h
        mbed/drivers/PortIn.h
        mbed/drivers/PortInOut.h
        mbed/drivers/PortOut.h
        mbed/drivers/PwmOut.h
        mbed/drivers/RawSerial.cpp
        mbed/drivers/RawSerial.h
        mbed/drivers/SPI.cpp
        mbed/drivers/SPI.h
        mbed/drivers/SPISlave.cpp
        mbed/drivers/SPISlave.h
        mbed/drivers/Serial.cpp
        mbed/drivers/Serial.h
        mbed/drivers/SerialBase.cpp
        mbed/drivers/SerialBase.h
        mbed/drivers/SerialWireOutput.h
        mbed/drivers/TableCRC.cpp
        mbed/drivers/TableCRC.h
        mbed/drivers/Ticker.cpp
        mbed/drivers/Ticker.h
        mbed/drivers/Timeout.cpp
        mbed/drivers/Timeout.h
        mbed/drivers/Timer.cpp
        mbed/drivers/Timer.h
        mbed/drivers/TimerEvent.cpp
        mbed/drivers/TimerEvent.h
        mbed/drivers/UARTSerial.cpp
        mbed/drivers/UARTSerial.h
        mbed/hal/analogin_api.h
        mbed/hal/analogout_api.h
        mbed/hal/buffer.h
        mbed/hal/can_api.h
        mbed/hal/can_helper.h
        mbed/hal/crc_api.h
        mbed/hal/critical_section_api.h
        mbed/hal/dma_api.h
        mbed/hal/ethernet_api.h
        mbed/hal/flash_api.h
        mbed/hal/gpio_api.h
        mbed/hal/gpio_irq_api.h
        mbed/hal/i2c_api.h
        mbed/hal/itm_api.h
        mbed/hal/lp_ticker_api.h
        mbed/hal/mbed_critical_section_api.c
        mbed/hal/mbed_flash_api.c
        mbed/hal/mbed_gpio.c
        mbed/hal/mbed_itm_api.c
        mbed/hal/mbed_lp_ticker_api.c
        mbed/hal/mbed_lp_ticker_wrapper.cpp
        mbed/hal/mbed_pinmap_common.c
        mbed/hal/mbed_sleep_manager.c
        mbed/hal/mbed_ticker_api.c
        mbed/hal/mbed_us_ticker_api.c
        mbed/hal/pinmap.h
        mbed/hal/port_api.h
        mbed/hal/pwmout_api.h
        mbed/hal/rtc_api.h
        mbed/hal/serial_api.h
        mbed/hal/sleep_api.h
        mbed/hal/spi_api.h
        mbed/hal/storage_abstraction/Driver_Common.h
        mbed/hal/storage_abstraction/Driver_Storage.h
        mbed/hal/ticker_api.h
        mbed/hal/trng_api.h
        mbed/hal/us_ticker_api.h
        mbed/mbed.h
        mbed/mbed_config.h
        mbed/platform/ATCmdParser.cpp
        mbed/platform/ATCmdParser.h
        mbed/platform/CThunk.h
        mbed/platform/CallChain.cpp
        mbed/platform/CallChain.h
        mbed/platform/Callback.h
        mbed/platform/CircularBuffer.h
        mbed/platform/CriticalSectionLock.h
        mbed/platform/DeepSleepLock.h
        mbed/platform/DirHandle.h
        mbed/platform/FileBase.cpp
        mbed/platform/FileBase.h
        mbed/platform/FileHandle.cpp
        mbed/platform/FileHandle.h
        mbed/platform/FileLike.h
        mbed/platform/FilePath.cpp
        mbed/platform/FilePath.h
        mbed/platform/FileSystemHandle.cpp
        mbed/platform/FileSystemHandle.h
        mbed/platform/FileSystemLike.h
        mbed/platform/FunctionPointer.h
        mbed/platform/LocalFileSystem.cpp
        mbed/platform/LocalFileSystem.h
        mbed/platform/NonCopyable.h
        mbed/platform/PlatformMutex.h
        mbed/platform/ScopedLock.h
        mbed/platform/SingletonPtr.h
        mbed/platform/Stream.cpp
        mbed/platform/Stream.h
        mbed/platform/Transaction.h
        mbed/platform/critical.h
        mbed/platform/mbed_alloc_wrappers.cpp
        mbed/platform/mbed_application.c
        mbed/platform/mbed_application.h
        mbed/platform/mbed_assert.c
        mbed/platform/mbed_assert.h
        mbed/platform/mbed_board.c
        mbed/platform/mbed_critical.c
        mbed/platform/mbed_critical.h
        mbed/platform/mbed_debug.h
        mbed/platform/mbed_error.c
        mbed/platform/mbed_error.h
        mbed/platform/mbed_error_hist.c
        mbed/platform/mbed_error_hist.h
        mbed/platform/mbed_interface.c
        mbed/platform/mbed_interface.h
        mbed/platform/mbed_mem_trace.cpp
        mbed/platform/mbed_mem_trace.h
        mbed/platform/mbed_mktime.c
        mbed/platform/mbed_mktime.h
        mbed/platform/mbed_poll.cpp
        mbed/platform/mbed_poll.h
        mbed/platform/mbed_power_mgmt.h
        mbed/platform/mbed_preprocessor.h
        mbed/platform/mbed_retarget.cpp
        mbed/platform/mbed_retarget.h
        mbed/platform/mbed_rtc_time.cpp
        mbed/platform/mbed_rtc_time.h
        mbed/platform/mbed_sdk_boot.c
        mbed/platform/mbed_semihost_api.c
        mbed/platform/mbed_semihost_api.h
        mbed/platform/mbed_sleep.h
        mbed/platform/mbed_stats.c
        mbed/platform/mbed_stats.h
        mbed/platform/mbed_toolchain.h
        mbed/platform/mbed_version.h
        mbed/platform/mbed_wait_api.h
        mbed/platform/mbed_wait_api_no_rtos.c
        mbed/platform/mbed_wait_api_rtos.cpp
        mbed/platform/platform.h
        mbed/platform/rtc_time.h
        mbed/platform/semihost_api.h
        mbed/platform/sleep.h
        mbed/platform/toolchain.h
        mbed/platform/wait_api.h
        mbed/targets/TARGET_STM/PeripheralPins.h
        mbed/targets/TARGET_STM/PinNamesTypes.h
        mbed/targets/TARGET_STM/PortNames.h

        mbed/targets/TARGET_STM/analogin_api.c
        mbed/targets/TARGET_STM/analogout_api.c
        mbed/targets/TARGET_STM/can_api.c
        mbed/targets/TARGET_STM/gpio_api.c
        mbed/targets/TARGET_STM/gpio_irq_api.c
        mbed/targets/TARGET_STM/gpio_object.h
        mbed/targets/TARGET_STM/hal_tick_overrides.c
        mbed/targets/TARGET_STM/i2c_api.c

        mbed/targets/TARGET_STM/mbed_crc_api.c
        mbed/targets/TARGET_STM/mbed_overrides.c
        mbed/targets/TARGET_STM/mbed_rtx.h
        mbed/targets/TARGET_STM/nvic_addr.h
        mbed/targets/TARGET_STM/pinmap.c
        mbed/targets/TARGET_STM/port_api.c
        mbed/targets/TARGET_STM/pwmout_api.c
        mbed/targets/TARGET_STM/rtc_api.c
        mbed/targets/TARGET_STM/rtc_api_hal.h
        mbed/targets/TARGET_STM/serial_api.c
        mbed/targets/TARGET_STM/serial_api_hal.h
        mbed/targets/TARGET_STM/sleep.c
        mbed/targets/TARGET_STM/stm32_assert.h
        mbed/targets/TARGET_STM/stm_spi_api.c
        mbed/targets/TARGET_STM/trng_api.c
        mbed/targets/TARGET_STM/us_ticker.c
        )