INCLUDE_DIRECTORIES(
        f7_simple_udp

        f7_simple_udp/Src
        f7_simple_udp/Inc

        f7_simple_udp/Middlewares
        f7_simple_udp/Middlewares/Third_Party
        f7_simple_udp/Middlewares/Third_Party/LwIP
        f7_simple_udp/Middlewares/Third_Party/LwIP/system
        f7_simple_udp/Middlewares/Third_Party/LwIP/system/arch
        f7_simple_udp/Middlewares/Third_Party/LwIP/src
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/core
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/core/ipv4
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/core/ipv6
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/netif
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/netif/ppp
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/posix
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/posix/sys
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/prot
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/priv
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/apps
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/netif
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/netif/ppp
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/api
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/apps
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/apps/mqtt
)

set(f7_simple_udp_files
        f7_simple_udp/Src/ethernetif.c
        f7_simple_udp/Src/lwip.c
        f7_simple_udp/Src/stm32f7xx_hal_msp.c
        f7_simple_udp/Src/stm32f7xx_it.c
        f7_simple_udp/Inc/ethernetif.h
        f7_simple_udp/Inc/lwip.h
        f7_simple_udp/Inc/lwipopts.h
        f7_simple_udp/Inc/main.h
        f7_simple_udp/Inc/stm32f7xx_it.h

        f7_simple_udp/Middlewares/Third_Party/LwIP/system/arch/epstruct.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/system/arch/sys_arch.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/system/arch/bpstruct.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/system/arch/cc.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/system/arch/lib.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/system/arch/cpu.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/system/arch/perf.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/system/arch/init.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/core/memp.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/core/sys.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/core/inet_chksum.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/core/raw.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/core/tcp_out.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/core/ip.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/core/dns.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/core/init.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/core/mem.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/core/def.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/core/udp.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/core/stats.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/core/tcp_in.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/core/ipv4/autoip.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/core/ipv4/dhcp.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/core/ipv4/igmp.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/core/ipv4/etharp.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/core/ipv4/icmp.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/core/ipv4/ip4.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/core/ipv4/ip4_frag.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/core/ipv4/ip4_addr.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/core/netif.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/core/tcp.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/core/pbuf.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/core/timeouts.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/core/ipv6/ip6.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/core/ipv6/icmp6.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/core/ipv6/mld6.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/core/ipv6/dhcp6.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/core/ipv6/ethip6.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/core/ipv6/nd6.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/core/ipv6/inet6.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/core/ipv6/ip6_addr.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/core/ipv6/ip6_frag.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/netif/ethernet.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/netif/slipif.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/netif/ppp/vj.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/netif/ppp/auth.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/netif/ppp/pppapi.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/netif/ppp/pppol2tp.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/netif/ppp/mppe.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/netif/ppp/eui64.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/netif/ppp/multilink.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/netif/ppp/pppoe.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/netif/ppp/chap_ms.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/netif/ppp/eap.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/netif/ppp/pppcrypt.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/netif/ppp/pppos.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/netif/ppp/lcp.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/netif/ppp/ipv6cp.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/netif/ppp/ccp.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/netif/ppp/utils.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/netif/ppp/chap-md5.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/netif/ppp/chap-new.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/netif/ppp/upap.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/netif/ppp/ecp.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/netif/ppp/magic.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/netif/ppp/fsm.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/netif/ppp/demand.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/netif/ppp/ppp.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/netif/ppp/ipcp.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/netif/lowpan6.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/posix/sys/socket.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/posix/netdb.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/posix/errno.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/pbuf.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/tcp.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/nd6.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/err.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/etharp.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/igmp.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/netif.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/sio.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/debug.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/ethip6.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/tcpip.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/ip4.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/icmp.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/timeouts.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/snmp.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/ip4_frag.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/ip6_addr.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/netifapi.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/inet.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/ip6_frag.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/ip4_addr.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/netbuf.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/api.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/dhcp.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/autoip.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/memp.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/prot/tcp.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/prot/nd6.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/prot/etharp.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/prot/igmp.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/prot/ip4.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/prot/icmp.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/prot/ethernet.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/prot/dhcp.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/prot/autoip.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/prot/ip6.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/prot/dns.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/prot/icmp6.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/prot/ip.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/prot/udp.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/prot/mld6.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/sockets.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/priv/tcpip_priv.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/priv/nd6_priv.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/priv/api_msg.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/priv/tcp_priv.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/priv/memp_priv.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/priv/memp_std.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/ip_addr.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/opt.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/inet_chksum.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/raw.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/ip6.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/sys.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/netdb.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/errno.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/def.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/mem.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/dns.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/icmp6.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/ip.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/init.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/dhcp6.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/apps/sntp.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/apps/snmp_opts.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/apps/httpd.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/apps/snmp_scalar.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/apps/snmpv3.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/apps/netbiosns_opts.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/apps/tftp_opts.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/apps/snmp_mib2.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/apps/mdns.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/apps/netbiosns.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/apps/snmp_core.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/apps/tftp_server.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/apps/snmp.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/apps/snmp_table.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/apps/httpd_opts.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/apps/lwiperf.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/apps/mdns_priv.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/apps/mqtt_opts.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/apps/mqtt.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/apps/snmp_threadsync.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/apps/mdns_opts.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/apps/fs.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/apps/sntp_opts.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/stats.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/udp.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/arch.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/lwip/mld6.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/netif/etharp.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/netif/lowpan6.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/netif/lowpan6_opts.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/netif/ppp/ccp.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/netif/ppp/chap-md5.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/netif/ppp/magic.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/netif/ppp/ecp.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/netif/ppp/upap.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/netif/ppp/chap-new.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/netif/ppp/ipcp.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/netif/ppp/ppp.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/netif/ppp/fsm.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/netif/ppp/pppdebug.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/netif/ppp/ppp_impl.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/netif/ppp/vj.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/netif/ppp/ppp_opts.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/netif/ppp/pppol2tp.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/netif/ppp/pppapi.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/netif/ppp/pppoe.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/netif/ppp/eui64.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/netif/ppp/mppe.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/netif/ppp/ipv6cp.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/netif/ppp/lcp.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/netif/ppp/pppos.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/netif/ppp/eap.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/netif/ppp/chap_ms.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/netif/ppp/pppcrypt.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/netif/ethernet.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/include/netif/slipif.h
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/api/sockets.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/api/netdb.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/api/tcpip.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/api/err.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/api/netifapi.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/api/api_lib.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/api/api_msg.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/api/netbuf.c
        f7_simple_udp/Middlewares/Third_Party/LwIP/src/apps/mqtt/mqtt.c
        f7_simple_udp/f7eth.cpp
        f7_simple_udp/f7eth.h
)

